### ISSUE TITLE
Bug: Editing Profil Form

### ISSUE THREAD

**Issue by ghost** [scg-unibe-ch/ese2016-team9#67]
Short description
When editing your profil, in particular the email, it shows a error when saving

Affected version
Release 2.0

Steps to reproduce
1. Log in as jane@doe.com
2. Click on the user image in the navigation
3. Click on 'User Profil'
4. Click on 'Edit Profil'
5. Change the Email like "test@unibe.ch"

**Comment by kellenberger** [comment]
Occurs only when changing username
